import { RecommendedArticle } from '../ets/viewmodel/RecommendedArticle'

export const recommendedArticleList: RecommendedArticle[] = [{
  isPinned: true,
  shortTitle: '聚首亚心之都，拥抱开源力量',
  fullTitle: '“聚首亚心之都，拥抱开源力量”| 2023 OpenHarmony城市推介会•乌鲁木齐市成功举办',
  author: 'OpenAtom OpenHarmony',
  date: '2023-11-08 21:00',
  fwdCnt: 152,
  cmtCnt: 38,
  likeCnt: 735,
  favCnt: 62
}, {
  isPinned: true,
  shortTitle: 'HarmonyOS语言基础类库开发指南上线啦！',
  fullTitle: 'HarmonyOS语言基础类库开发指南上线啦！',
  author: 'HarmonyOS开发者',
  date: '2023-10-18 20:07',
  fwdCnt: 93,
  cmtCnt: 0,
  likeCnt: 952,
  favCnt: 14
}, {
  isPinned: false,
  shortTitle: '第二届OpenHarmony技术大会精彩瞬间',
  fullTitle: '高能回顾 | 第二届OpenHarmony技术大会精彩瞬间',
  author: 'OpenAtom OpenHarmony',
  date: '2023-11-07 21:00',
  fwdCnt: 63,
  cmtCnt: 94,
  likeCnt: 1852,
  favCnt: 54
}]
