/*
 * Copyright (c) 2023 Southeast University.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


import { RecommendedVideo } from '../ets/viewmodel/RecommendedVideo'

export const recommendedVideoList: RecommendedVideo[] = [{
  shortTitle: '打造高校生态链 OpenHarmony技术俱乐部分论坛召开',
  fullTitle: '打造高校生态链 OpenHarmony技术俱乐部分论坛召开',
  author: 'OpenAtom OpenHarmony',
  date: '2023-11-07 21:00',
  cover: $r("app.media.fig_1"),
  duration: 362,
  fwdCnt: 84,
  cmtCnt: 275,
  likeCnt: 1856,
  favCnt: 52
}, {
  shortTitle: '首届OpenHarmony竞赛训练营结营颁奖',
  fullTitle: '首届OpenHarmony竞赛训练营结营颁奖，75所高校学子助力建设开源生态',
  author: 'OpenAtom OpenHarmony',
  date: '2023-11-06 19:30',
  cover: $r("app.media.fig_2"),
  duration: 298,
  fwdCnt: 22,
  cmtCnt: 17,
  likeCnt: 1362,
  favCnt: 410
}]
