/*
 * Copyright (c) 2023 Southeast University.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


export const trendingSearchList:string[] = [
  '树莓派4B开发板通过OpenHarmony兼容性测评',
  'OpenHarmony正式落地水利行业：多款产品通过兼容性测评',
  '持续使能智慧医疗，新增三款搭载润开鸿HiHopeOS智能药品柜通过OpenHarmony兼容性测评',
  '润开鸿龙芯交通控制器设备通过OpenHarmony兼容性测评',
  '2024年首期OpenHarmony繁星计划师资培训在东莞圆满举办',
  '开源大师兄开发板通过OpenHarmony 3.2 Release版本兼容性测评'
]