/*
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License')
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ComponentTextRicheditorFontfeatures
  from './ComponentTextRicheditorFontfeatureTest/ComponentTextRicheditorFontfeatures.test';
import ComponentTextRicheditorCustomColors
  from './ComponentTextRicheditorCustomColorsTest/ComponentTextRicheditorCustomColors.test';
import ComponentTextRicheditorWordbreaks
  from './ComponentTextRicheditorWordbreakTest/ComponentTextRicheditorWordbreaks.test';
import ComponentTextRicheditorLongPresstoselectalls
  from './ComponentTextRicheditorLongPresstoselectallTest/ComponentTextRicheditorLongPresstoselectalls.test';
import ComponentTextRicheditorPlaceholderTests
  from './ComponentTextRicheditorPlaceholderTest/ComponentTextRicheditorPlaceholderTests.test';

import ComponentTextRicheditorCustomkeyBoardAvoidAnceTests
  from './ComponentTextRicheditorCustomkeyBoardAvoidAnceTest/ComponentTextRicheditorCustomkeyBoardAvoidAnceTests.test';
import ComponentTextRicheditorKeyboardReinForcingTests
  from './ComponentTextRicheditorKeyboardReinForcingTest/ComponentTextRicheditorKeyboardReinForcingTests.test';
import ComponentTextRicheditorLineHeightLetterSpacingTests
  from './ComponentTextRicheditorLineHeightLetterSpacing/ComponentTextRicheditorLineHeightLetterSpacingTests.test';
import ComponentTextRicheditorUxConformanceTests
  from './ComponentTextRicheditorUxConformanceTest/ComponentTextRicheditorUxConformanceTests.test';
import ComponentTextRicheditorAITests from './ComponentTextRicheditorAITest/ComponentTextRicheditorAITests.test';
import ComponentTextRicheditorOnWillChangeTests
  from './ComponentTextRicheditorOnWillChangeTest/ComponentTextRicheditorOnWillChangeTests.test';
import ComponentTextRicheditorInterfaceTests
  from './ComponentTextRicheditorInterface/ComponentTextRicheditorInterfaceTests.test';
import ComponentTextRicheditorShortKcutKeysTests
  from './ComponentTextRicheditorShortKcutKeys/ComponentTextRicheditorShortKcutKeysTests.test';

import UIComponentNavTabsOnWillShow from './UIComponentNavTabsOnWillShowTest/UIComponentNavTabsOnWillShow.test';
import UIComponentNavTabsContentAdapt from './UIComponentNavTabsContentAdaptTest/UIComponentNavTabsContentAdapt.test';
import ArkUITabScrollable from './ArkUITabScrollableTest/ArkUITabScrollable.test';
import ArkUITabsLabelStylefont from './ArkUITabsLabelStylefontTest/ArkUITabsLabelStylefont.test';
import ArkUITabsLabelStyleSelectedColor
  from './ArkUITabsLabelStyleSelectedColorTest/ArkUITabsLabelStyleSelectedColor.test';
import ArkUITabsLabelStyleUnselectedColor
  from './ArkUITabsLabelStyleUnselectedColorTest/ArkUITabsLabelStyleUnselectedColor.test';
import UIComponentListAndGridWaterFlowAdd
  from './UIComponentListAndGridWaterFlowAddTest/UIComponentListAndGridWaterFlowAdd.test';
import UIComponentListAndGridWaterSections
  from './UIComponentListAndGridWaterSectionsTest/UIComponentListAndGridWaterSections.test';
import UIComponentNavModifier from './UIComponentNavModifierTest/UIComponentNavModifier.test';
import UIComponentNavTabsAction from './UIComponentNavTabsActionTest/UIComponentNavTabsAction.test';
import UIComponentNavTabsBlurStyle from './UIComponentNavTabsBlurStyleTest/UIComponentNavTabsBlurStyle.test';
import UIComponentNavTabsCachedCount from './UIComponentNavTabsCachedCountTest/UIComponentNavTabsCachedCount.test';
import UIComponentNavTabsImproTrace from './UIComponentNavTabsImproTraceTest/UIComponentNavTabsImproTrace.test';
import UIComponentNavTabsInterception from './UIComponentNavTabsInterceptionTest/UIComponentNavTabsInterception.test';
import UIComponentNavTabsInterface from './UIComponentNavTabsInterfaceTest/UIComponentNavTabsInterface.test';
import UIComponentNavTabsMirror from './UIComponentNavTabsMirrorTest/UIComponentNavTabsMirror.test';
import UIComponentTabTabBarSymbol from './UIComponentTabTabBarSymbolTest/UIComponentTabTabBarSymbol.test';
import UIComponentOtherRefreshPromptText
  from './UIComponentOtherRefreshPromptTextTest/UIComponentOtherRefreshPromptText.test';
import UIComponentOtherRefreshInterface
  from './UIComponentOtherRefreshInterfaceTest/UIComponentOtherRefreshInterface.test';
import UIComponentOtherRefreshInterAction
  from './UIComponentOtherRefreshInterActionTest/UIComponentOtherRefreshInterAction.test';
import UIComponentOtherRefreshAbility from './UIComponentOtherRefreshAbilityTest/UIComponentOtherRefreshAbility.test';
import FunctionJichuWaterFlow from './FunctionJichuWaterFlowTest/FunctionJichuWaterFlow.test';
import UIComponentNavTabsSubTabbarStyle
  from './UIComponentNavTabsSubTabbarStyleTest/UIComponentNavTabsSubTabbarStyle.test';
import ArkUITabsVertical from './ArkUITabsVerticalTest/ArkUITabsVertical.test';
import UIComponentNavTabsHeight from './UIComponentNavTabsHeightTest/UIComponentNavTabsHeight.test';
import UIComponentNavTabsWidth from './UIComponentNavTabsWidthTest/UIComponentNavTabsWidth.test';
import UIComponentNavTabsEdgeeffect from './UIComponentNavTabsEdgeeffectTest/UIComponentNavTabsEdgeeffect.test';
import UIComponentNavTabsExpandsafearea
  from './UIComponentNavTabsExpandsafeareaTest/UIComponentNavTabsExpandsafearea.test';
import ArkUITabsIconStyleSelectedColor
  from './ArkUITabsIconStyleSelectedColorTest/ArkUITabsIconStyleSelectedColor.test';
import ArkUITabsIconStyleUnselectedColor
  from './ArkUITabsIconStyleUnselectedColorTest/ArkUITabsIconStyleUnselectedColor.test';
import ArkUITabsSingleSelectedcolor from './ArkUITabsSingleSelectedcolorTest/ArkUITabsSingleSelectedcolor.test';
import ArkUITabsSingleUnselectedcolor from './ArkUITabsSingleUnselectedcolorTest/ArkUITabsSingleUnselectedcolor.test';
import UIComponentScrollSwiperLayout from './UIComponentScrollSwiperLayoutTest/UIComponentScrollSwiperLayout.test';
import UIComponentScrollSwiperUx from './UIComponentScrollSwiperUxTest/UIComponentScrollSwiperUx.test';
import UIComponentScrollSwiperInterface
  from './UIComponentScrollSwiperInterfaceTest/UIComponentScrollSwiperInterface.test';
import UIComponentScrollSwiperAcross from './UIComponentScrollSwiperAcrossTest/UIComponentScrollSwiperAcross.test';
import UIComponentScrollSwiperTeace from './UIComponentScrollSwiperTeaceTest/UIComponentScrollSwiperTeace.test';
import UIComponentScrollSwiperDisplaycount
  from './UIComponentScrollSwiperDisplaycountTest/UIComponentScrollSwiperDisplaycount.test';
import UIComponentScrollSwiperArrowHead
  from './UIComponentScrollSwiperArrowHeadTest/UIComponentScrollSwiperArrowHead.test';
import UIComponentSpecialComponentsFormComponentTransparent
  from './UIComponentSpecialComponentsFormComponentTransparentTest/UIComponentSpecialComponentsFormComponentTransparent.test';
import UIComponentSpecialComponentsUIExtensionComponentPopupChange
  from './UIComponentSpecialComponentsUIExtensionComponentPopupChangeTest/UIComponentSpecialComponentsUIExtensionComponentPopupChange.test';

import UIComponentPopupBoxSpecificationsShadow
  from './UIComponentPopupBoxSpecificationsShadowTest/UIComponentPopupBoxSpecificationsShadow.test';
import UIComponentButtonRadioLConic from './UIComponentButtonRadioLConicTest/UIComponentButtonRadioLConic.test';
import ComponentFunctionLAdvancedComponentsPopupInterface
  from './ComponentFunctionLAdvancedComponentsPopupInterfaceTest/ComponentFunctionLAdvancedComponentsPopupInterface.test';
import UIComponentPopupBoxSpecifications
  from './UIComponentPopupBoxSpecificationsTest/UIComponentPopupBoxSpecifications.test';
import UIComponentButtonStyle from './UIComponentButtonStyleTest/UIComponentButtonStyle.test';
import UIComponentButtonRadioCustonmizing
  from './UIComponentButtonRadioCustonmizingTest/UIComponentButtonRadioCustonmizing.test';
import UIComponentButtonRadioCheckMark
  from './UIComponentButtonRadioCheckMarkTest/UIComponentButtonRadioCheckMark.test';
import UIComponentButtonSelectAttribute
  from './UIComponentButtonSelectAttributeTest/UIComponentButtonSelectAttribute.test';
import UIComponentFunctionSelectSymbol from './UIComponentFunctionSelectSymbol/UIComponentFunctionSelectSymbol.test';
import UIComponentButtonSelectControlSize
  from './UIComponentButtonSelectControlSize/UIComponentButtonSelectControlSize.test';
import UIComponentButtonSelectDivider from './UIComponentButtonSelectDivider/UIComponentButtonSelectDivider.test';
import UITestCaseTest from './UITestCaseTest/UITestCaseTest.test';
import FunctionJiChuSR000HUB4K from './FunctionJiChuSR000HUB4KTest/FunctionJiChuSR000HUB4K.test';
import UIComponentUISupportColor from './UIComponentUISupportColorTest/UIComponentUISupportColor.test';
import UIComponentButtonCommonButton from './UIComponentButtonCommonButtonTest/UIComponentButtonCommonButton.test'
import ComponentButtonSelectMenuItemContentModifier
  from './ComponentButtonSelectMenuItemContentModifier/ComponentButtonSelectMenuItemContentModifier.test';
import UiComponentButtonSelectEnhancement
  from './UiComponentButtonSelectEnhancement/UiComponentButtonSelectEnhancement.test';
import UiComponentButtonSelectAlign from './UiComponentButtonSelectAlign/UiComponentButtonSelectAlign.test';
import UiComponentPopupboxZero from './UiComponentPopupboxZero/UiComponentPopupboxZero.test';
import UIComponentPopupboxCalendarpickerInterface
  from './UIComponentPopupboxCalendarpickerInterfaceTest/UIComponentPopupboxCalendarpickerInterface.test';
import UIComponentPopupboxDatepickerDialogLanguageHabit
  from './UIComponentPopupboxDatepickerDialogLanguageHabitTest/UIComponentPopupboxDatepickerDialogLanguageHabit.test';
import TsComponentSR000HRP34 from './TsComponentSR000HRP34Test/TsComponentSR000HRP34Test.test';
import UiComponentPopupboxDatePickerDialogScenarios
  from './UiComponentPopupboxDatePickerDialogScenarios/UiComponentPopupboxDatePickerDialogScenarios.test';
import UiComponentPopupboxDatePickerDialogInterface
  from './UiComponentPopupboxDatePickerDialogInterface/UiComponentPopupboxDatePickerDialogInterface.test';
import UIComponentPopupBoxAttribute from './UIComponentPopupBoxAttributeTest/UIComponentPopupBoxAttribute.test';
import UIComponentPopupBoxPromptToastSequence
  from './UIComponentPopupBoxPromptToastSequenceTest/UIComponentPopupBoxPromptToastSequence.test';
import UIComponentPopupBoxSpecificationsPopup
  from './UIComponentPopupBoxSpecificationsPopupTest/UIComponentPopupBoxSpecificationsPopup.test';

import UIComponentPopupBoxPopupInterface001
  from './UIComponentPopupBoxPopupInterfaceTest/UIComponentPopupBoxPopupInterface001.test';
import UIComponentPopupPromptInterface001
  from './UIComponentPopupPromptInterfaceTest/UIComponentPopupPromptInterface001.test';
import UIComponentPopupBoxToastStyleInterface001
  from './UIComponentPopupBoxToastStyleInterfaceTest/UIComponentPopupBoxToastStyleInterface001.test';
import UIComponentPopupBoxFullDialogInterface001
  from './UIComponentPopupBoxFullDialogInterfaceTest/UIComponentPopupBoxFullDialogInterface001.test';

export default function testsuite() {
  ComponentTextRicheditorFontfeatures();
  ComponentTextRicheditorCustomColors();
  ComponentTextRicheditorWordbreaks();
  ComponentTextRicheditorLongPresstoselectalls();
  ComponentTextRicheditorPlaceholderTests();
  ComponentTextRicheditorCustomkeyBoardAvoidAnceTests();
  ComponentTextRicheditorKeyboardReinForcingTests();
  ComponentTextRicheditorLineHeightLetterSpacingTests();
  ComponentTextRicheditorUxConformanceTests();
  ComponentTextRicheditorAITests();
  ComponentTextRicheditorOnWillChangeTests();
  ComponentTextRicheditorInterfaceTests();
  ComponentTextRicheditorShortKcutKeysTests();

  UIComponentNavTabsOnWillShow();
  UIComponentNavTabsContentAdapt();
  ArkUITabScrollable();
  ArkUITabsLabelStylefont();
  ArkUITabsLabelStyleSelectedColor();
  ArkUITabsLabelStyleUnselectedColor();
  UIComponentListAndGridWaterFlowAdd();
  UIComponentListAndGridWaterSections();
  UIComponentNavModifier();
  UIComponentNavTabsAction();
  UIComponentNavTabsBlurStyle();
  UIComponentNavTabsCachedCount();
  UIComponentNavTabsImproTrace();
  UIComponentNavTabsInterception();
  UIComponentNavTabsInterface();
  UIComponentNavTabsMirror();
  UIComponentTabTabBarSymbol();
  UIComponentOtherRefreshPromptText();
  UIComponentOtherRefreshInterface();
  UIComponentOtherRefreshInterAction();
  UIComponentOtherRefreshAbility();
  FunctionJichuWaterFlow();
  UIComponentNavTabsSubTabbarStyle();
  ArkUITabsVertical();
  UIComponentNavTabsHeight();
  UIComponentNavTabsWidth();
  UIComponentNavTabsEdgeeffect();
  UIComponentNavTabsExpandsafearea();
  ArkUITabsIconStyleSelectedColor();
  ArkUITabsIconStyleUnselectedColor();
  ArkUITabsSingleSelectedcolor();
  ArkUITabsSingleUnselectedcolor();

  UIComponentScrollSwiperLayout();
  UIComponentScrollSwiperUx();
  UIComponentScrollSwiperInterface();
  UIComponentScrollSwiperAcross();
  UIComponentScrollSwiperTeace();
  UIComponentScrollSwiperDisplaycount();
  UIComponentScrollSwiperArrowHead();

  UIComponentPopupBoxFullDialogInterface001();
  UIComponentPopupBoxToastStyleInterface001();
  UIComponentPopupPromptInterface001();
  UIComponentPopupBoxPopupInterface001();
  UIComponentButtonStyle();
  UIComponentButtonRadioLConic();
  ComponentFunctionLAdvancedComponentsPopupInterface();
  UIComponentPopupBoxSpecifications();
  UIComponentButtonRadioCustonmizing();
  UIComponentButtonRadioCheckMark();
  UIComponentButtonSelectAttribute();
  UIComponentSpecialComponentsFormComponentTransparent();
  UIComponentSpecialComponentsUIExtensionComponentPopupChange();
  UIComponentPopupBoxSpecificationsShadow();
  UIComponentFunctionSelectSymbol();
  UIComponentButtonSelectControlSize();
  UIComponentButtonSelectDivider();
  UITestCaseTest();
  FunctionJiChuSR000HUB4K();
  UIComponentUISupportColor();
  UIComponentButtonCommonButton();
  ComponentButtonSelectMenuItemContentModifier();
  UiComponentButtonSelectEnhancement();
  UiComponentButtonSelectAlign();
  UiComponentPopupboxZero();
  UIComponentPopupboxCalendarpickerInterface();
  UIComponentPopupboxDatepickerDialogLanguageHabit();
  TsComponentSR000HRP34();
  UiComponentPopupboxDatePickerDialogScenarios();
  UiComponentPopupboxDatePickerDialogInterface();
  UIComponentPopupBoxAttribute();
  UIComponentPopupBoxPromptToastSequence();
  UIComponentPopupBoxSpecificationsPopup();
}


