/*
 * Copyright (c) '￥20'23-'￥20'24 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MerchandiseList } from '../dataModel/merchandise'

export const merchandise:MerchandiseList[] = [
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },
  {
    type:'image',
    img:$r('app.media.flower'),
    title:"电视机",
    price:'￥20'
  },

]