/*
 * Copyright (c) 2023 Southeast University.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const IMG_POOL: Resource[] = [
  $r('app.media.fig_1'),
  $r('app.media.fig_2'),
  $r('app.media.fig_3'),
  $r('app.media.fig_4'),
  $r('app.media.fig_5'),
  $r('app.media.fig_6'),
  $r('app.media.fig_7'),
  $r('app.media.fig_8'),
  $r('app.media.fig_9'),
  $r('app.media.fig_10'),
  $r('app.media.fig_11'),
  $r('app.media.fig_12'),
  $r('app.media.fig_13'),
  $r('app.media.fig_14'),
  $r('app.media.fig_15'),
  $r('app.media.fig_16'),
  $r('app.media.fig_17'),
  $r('app.media.fig_18'),
  $r('app.media.fig_19'),
  $r('app.media.fig_20')
]